<?php
// 20220702045 Ece Duzgec

//  Loads every value that appears in the database from .txt file

// Helper
function readLines(string $file): array {
    if (!file_exists($file)) die("Missing input file: $file\n");
    $lines = file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    return array_map('trim', $lines);
}

// Reads videos.txt separated by tabs url, title, description per line.
function readVideos(string $file): array {
    if (!file_exists($file)) die("Missing input file: $file\n");
    $rows = [];
    foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') continue;
        $parts = explode("\t", $line);
        if (count($parts) < 3) {
            die("Bad line in $file (need 3 tab-separated fields):\n  $line\n");
        }
        $rows[] = [
            'url'   => trim($parts[0]),
            'title' => trim($parts[1]),
            'desc'  => trim($parts[2]),
        ];
    }
    if (empty($rows)) die("$file has no valid rows.\n");
    return $rows;
}

function esc(string $val): string {
    return str_replace("'", "''", $val);
}

function randDate(int $yearFrom, int $yearTo): string {
    $y = rand($yearFrom, $yearTo);
    $m = str_pad(rand(1, 12), 2, '0', STR_PAD_LEFT);
    $d = str_pad(rand(1, 28), 2, '0', STR_PAD_LEFT);
    return "$y-$m-$d";
}

function randDateTime(int $yearFrom, int $yearTo): string {
    $date = randDate($yearFrom, $yearTo);
    $h    = str_pad(rand(0, 23), 2, '0', STR_PAD_LEFT);
    $min  = str_pad(rand(0, 59), 2, '0', STR_PAD_LEFT);
    return "$date $h:$min:00";
}

// Load all input files 

// USERS
$firstNames    = readLines('first_names.txt');
$lastNames     = readLines('last_names.txt');
$bios          = readLines('bios.txt');
$countries     = readLines('countries.txt');
$userImages    = readLines('user_image_urls.txt');

// CHANNELS
$channelNames  = readLines('channel_names.txt');
$channelDescs  = readLines('channel_descriptions.txt');
$categories    = readLines('categories.txt');
$channelImages = readLines('channel_image_urls.txt');

// VIDEOS 
$videos        = readVideos('videos.txt');
$videoCount    = count($videos);

// COMMENTS
$commentBodies = readLines('comment_bodies.txt');
$replyBodies   = readLines('reply_bodies.txt');

// Build SQL 
$sql .= "  MiniTube seed.sql — auto-generated by generate_data.php\n";
$sql .= "  " . date('Y-m-d H:i:s') . "\n";
$sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

//1. USERS (100) 
$sql .= " USERS\n";

$fnCount  = count($firstNames);
$lnCount  = count($lastNames);
$bioCount = count($bios);
$coCount  = count($countries);
$uiCount  = count($userImages);

for ($i = 1; $i <= 100; $i++) {
    $fn       = $firstNames[($i - 1) % $fnCount];
    $ln       = $lastNames[($i - 1) % $lnCount];

    // username: lowercase letters/numbers of first name + zero-padded index
    $username = strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $fn))
                . str_pad($i, 2, '0', STR_PAD_LEFT);

    // password: uppercase letters of first name + reversed index + "!"
    $num      = str_pad($i, 2, '0', STR_PAD_LEFT);
    $password = strtoupper(preg_replace('/[^a-zA-Z]/', '', $fn)) . strrev($num) . '!';

    $fullName = esc($fn . ' ' . $ln);
    $email    = esc($username . '@minitube.com');
    $country  = esc($countries[($i - 1) % $coCount]);
    $joined   = randDate(2015, 2023);
    $img      = esc($userImages[($i - 1) % $uiCount]);
    $bio      = "'" . esc($bios[($i - 1) % $bioCount]) . "'";

    $sql .= "INSERT INTO USERS "
          . "(username, password, user_image, full_name, email, country, joined_on, bio) "
          . "VALUES ('$username', '$password', '$img', '$fullName', "
          .         "'$email', '$country', '$joined', $bio);\n";
}

// 2. CHANNELS (50) 
$sql .= "\n CHANNELS\n";

$chCount   = count($channelNames);
$cdCount   = count($channelDescs);
$catCount  = count($categories);
$ciCount   = count($channelImages);

for ($i = 1; $i <= 50; $i++) {
    $name     = esc($channelNames[($i - 1) % $chCount]);
    $desc     = "'" . esc($channelDescs[($i - 1) % $cdCount]) . "'";
    $img      = esc($channelImages[($i - 1) % $ciCount]);
    $category = esc($categories[($i - 1) % $catCount]);
    $created  = randDate(2015, 2022);

    $sql .= "INSERT INTO CHANNELS "
          . "(owner_id, channel_image, name, description, created_on, category) "
          . "VALUES ($i, '$img', '$name', $desc, '$created', '$category');\n";
}

// 3. VIDEOS (200) 
$sql .= "\n VIDEOS\n";

for ($i = 1; $i <= 200; $i++) {
    $channelId = (($i - 1) % 50) + 1;
    $v         = $videos[($i - 1) % $videoCount];
    $url       = esc($v['url']);
    $title     = esc($v['title']);
    $desc      = "'" . esc($v['desc']) . "'";
    $duration  = rand(60, 3600);
    $uploaded  = randDateTime(2022, 2025);
    $views     = rand(0, 50000);
    $likes     = rand(0, (int)($views * 0.1));

    $sql .= "INSERT INTO VIDEOS "
          . "(channel_id, title, description, url, duration_seconds, uploaded_at, view_count, like_count) "
          . "VALUES ($channelId, '$title', $desc, '$url', $duration, '$uploaded', $views, $likes);\n";
}

// 4. SUBSCRIPTIONS (200) 
$sql .= "\n SUBSCRIPTIONS\n";

$pairs    = [];
$subCount = 0;
$attempts = 0;
srand(42);

while ($subCount < 200 && $attempts < 20000) {
    $attempts++;
    $sid = rand(1, 100);
    $cid = rand(1, 50);
    // Users 1-50 own channels 1-50 to prevent self subscription
    if ($sid <= 50 && $sid === $cid) continue;
    $key = "$sid-$cid";
    if (isset($pairs[$key])) continue;
    $pairs[$key] = true;
    $subCount++;
    $sql .= "INSERT INTO SUBSCRIPTIONS (subscriber_id, channel_id, subscribed_at) "
          . "VALUES ($sid, $cid, '" . randDateTime(2022, 2025) . "');\n";
}

// 5. COMMENTS 
// Strips any comment body that is fewer than 10 characters so and single letter entries cannot make it into the database.
$commentBodies = array_values(array_filter($commentBodies, fn($b) => strlen($b) >= 10));
$replyBodies   = array_values(array_filter($replyBodies,   fn($b) => strlen($b) >= 10));

if (empty($commentBodies)) die("comment_bodies.txt has no valid entries (need >= 10 chars each).\n");
if (empty($replyBodies))   die("reply_bodies.txt has no valid entries (need >= 10 chars each).\n");

// 600 top level comments distributed across all 200 videos (3 per video on average). and 400 threaded replies across as threads.

$sql .= "\n COMMENTS (top-level)\n";

$cbCount = count($commentBodies);
$topLevelVideoIds = [];

for ($i = 1; $i <= 600; $i++) {
    $videoId  = (($i - 1) % 200) + 1;
    $userId   = (($i - 1) % 100) + 1;
    $body     = esc($commentBodies[($i - 1) % $cbCount]);
    $postedAt = randDateTime(2022, 2025);
    $topLevelVideoIds[$i] = $videoId;

    $sql .= "INSERT INTO COMMENTS (video_id, user_id, parent_comment_id, body, posted_at) "
          . "VALUES ($videoId, $userId, NULL, '$body', '$postedAt');\n";
}

$sql .= "\n COMMENTS (replies — wave 1: one reply each on comments 1-250)\n";

$rbCount = count($replyBodies);

for ($i = 0; $i < 250; $i++) {
    $parentId = $i + 1;
    $videoId  = $topLevelVideoIds[$parentId];
    $userId   = (($i + 17) % 100) + 1;
    $body     = esc($replyBodies[$i % $rbCount]);
    $postedAt = randDateTime(2023, 2025);

    $sql .= "INSERT INTO COMMENTS (video_id, user_id, parent_comment_id, body, posted_at) "
          . "VALUES ($videoId, $userId, $parentId, '$body', '$postedAt');\n";
}

$sql .= "\n COMMENTS (replies — wave 2: second reply on comments 1-100 for multi-reply threads)\n";

for ($i = 0; $i < 100; $i++) {
    $parentId = ($i % 100) + 1;
    $videoId  = $topLevelVideoIds[$parentId];
    $userId   = (($i + 37) % 100) + 1;
    $body     = esc($replyBodies[($i + 13) % $rbCount]);
    $postedAt = randDateTime(2023, 2025);

    $sql .= "INSERT INTO COMMENTS (video_id, user_id, parent_comment_id, body, posted_at) "
          . "VALUES ($videoId, $userId, $parentId, '$body', '$postedAt');\n";
}

$sql .= "\n COMMENTS (replies — wave 3: third reply on first 50 comments for deep threads)\n";

for ($i = 0; $i < 50; $i++) {
    $parentId = ($i % 50) + 1;
    $videoId  = $topLevelVideoIds[$parentId];
    $userId   = (($i + 53) % 100) + 1;
    $body     = esc($replyBodies[($i + 27) % $rbCount]);
    $postedAt = randDateTime(2024, 2025);

    $sql .= "INSERT INTO COMMENTS (video_id, user_id, parent_comment_id, body, posted_at) "
          . "VALUES ($videoId, $userId, $parentId, '$body', '$postedAt');\n";
}

$sql .= "\nSET FOREIGN_KEY_CHECKS=1;\n";

//  Write seed.sql 
$outputFile = 'seed.sql';
if (file_put_contents($outputFile, $sql) === FALSE) {
    die("Failed to write $outputFile — check folder permissions.\n");
}

// Summary
echo "<pre>";
echo "seed.sql generated successfully!\n\n";
echo "Input files read:\n";
echo "  USERS:\n";
echo "    first_names.txt          -> " . count($firstNames)    . " entries\n";
echo "    last_names.txt           -> " . count($lastNames)      . " entries\n";
echo "    bios.txt                 -> " . count($bios)           . " entries\n";
echo "    countries.txt            -> " . count($countries)      . " entries\n";
echo "    user_image_urls.txt      -> " . count($userImages)     . " entries\n";
echo "  CHANNELS:\n";
echo "    channel_names.txt        -> " . count($channelNames)   . " entries\n";
echo "    channel_descriptions.txt -> " . count($channelDescs)   . " entries\n";
echo "    categories.txt           -> " . count($categories)     . " entries\n";
echo "    channel_image_urls.txt   -> " . count($channelImages)  . " entries\n";
echo "  VIDEOS:\n";
echo "    videos.txt               -> " . count($videos)         . " entries (url + title + desc)\n";
echo "  COMMENTS:\n";
echo "    comment_bodies.txt       -> " . count($commentBodies)  . " entries\n";
echo "    reply_bodies.txt         -> " . count($replyBodies)    . " entries\n\n";
echo "Rows written to seed.sql:\n";
echo "  USERS         -> 100\n";
echo "  CHANNELS      -> 50\n";
echo "  VIDEOS        -> 200\n";
echo "  SUBSCRIPTIONS -> $subCount\n";
echo "  COMMENTS      -> 1000 (600 top-level + 400 threaded replies across 3 waves)\n\n";
echo "Run install.php to load seed.sql into the database.\n";
echo "</pre>";
?>
